# Generated by Django 4.2.7 on 2023-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('email', models.TextField(db_column='email', null=True)),
                ('number', models.PositiveBigIntegerField(db_column='number', null=True)),
                ('password', models.TextField(db_column='password', null=True)),
            ],
        ),
    ]
