# Generated by Django 4.2.7 on 2023-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('number', models.PositiveBigIntegerField(db_column='number', null=True)),
                ('time', models.TimeField(db_column='time', null=True)),
                ('address', models.TextField(db_column='address', max_length=500, null=True)),
                ('location', models.TextField(db_column='location', null=True)),
                ('specialist', models.TextField(db_column='speciallist', null=True)),
                ('doctors', models.TextField(db_column='doc', null=True)),
                ('msg', models.TextField(db_column='message', null=True)),
            ],
            options={
                'db_table': 'general_booking',
            },
        ),
    ]
