# Generated by Django 4.2.7 on 2023-12-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='patient_contact',
        ),
    ]
