# Generated by Django 5.0 on 2023-12-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_alter_contact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.PositiveBigIntegerField(db_column='mob', null=True),
        ),
    ]
