# Generated by Django 5.0 on 2023-12-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adddoctor',
            table='Add_doctor',
        ),
    ]
