# Generated by Django 5.0 on 2023-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0002_alter_adddoctor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddoctor',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='adddoctor',
            name='doc_id',
            field=models.PositiveIntegerField(db_column='doc_id', null=True),
        ),
        migrations.AlterModelTable(
            name='adddoctor',
            table='add_doctor',
        ),
    ]
