# Generated by Django 5.0 on 2023-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0003_remove_adddoctor_roll_no_adddoctor_doc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoctor',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='images'),
        ),
    ]
