# Generated by Django 5.0 on 2023-12-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0004_adddoctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddoctor',
            name='name',
        ),
    ]
