# Generated by Django 5.0 on 2023-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0005_remove_adddoctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddoctor',
            name='age',
            field=models.PositiveIntegerField(db_column='age', null=True),
        ),
    ]
