# Generated by Django 5.0 on 2023-12-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0006_alter_adddoctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddoctor',
            name='doc_id',
            field=models.PositiveBigIntegerField(db_column='doc_id', null=True),
        ),
        migrations.AlterField(
            model_name='adddoctor',
            name='number',
            field=models.PositiveBigIntegerField(db_column='number', null=True),
        ),
    ]
